# Generated by Django 3.2.4 on 2021-06-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20210618_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='numero_calle',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
    ]
